<?php
enum BotState {
  case START;
  case CHOOSE_ACTION;
  case READ_DAYS_WERE_LISTED;
  case READ_GIVE_RESULT;
  case WRITE_DAYS_WERE_LISTED;
  case WRITE_ACTIONS_WERE_LISTED;
  case TASK_NUMBER_TO_REMOVE_WAS_CHOSEN;
  case WRITE_INSERT_INDEX_WAS_CHOSEN;
  case WRITE_INSERT_TASK_NAME_WAS_GIVEN;
  case WRITE_UPDATE_INDEX_WAS_CHOSEN;
  case WRITE_UPDATE_TASK_NAME_WAS_GIVEN;
}
?>